site:
  title: Antora Docs
  start_page: example-a::index.adoc
content:
  sources:
    - url: https://github.com/PardusEidolon/example-a
      branches: [main,v2.0]
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
